### ISSUE TITLE
Simplify the handling of parameterized types

### ISSUE THREAD

**Issue by metacosm** [quarkusio/gizmo#66]
Right now, you need to use `signature` passing it a complex string describing how your type is parameterized. It would be nice if that complexity could be hidden away.

**Comment by dufoli** [comment]
currently, when Class is parameterized, we need to add signature like that:

```
String signature = String.format("Ljavax/enterprise/util/AnnotationLiteral<L%1$s;>;L%1$s;",
        eventAnnotationLiteral.getName().toString().replace('.', '/'));

ClassCreator literalClassCreator = ClassCreator.builder().classOutput(classOutput)
        .className(literalClassName)
        .signature(signature)
        .superClass(AnnotationLiteral.class)
        .interfaces(eventAnnotationLiteral.getName().toString())
        .build();
```

I have introduce on PR a signature generation.

**Comment by dufoli** [comment]
ok so now code is ready for review. I do not think it is ready for merge but size of patch need review to know If I go on right direction. I try to not break API which lead to some stuff
- formalType is added after MethodDescriptor to avoid break of signature of current API
- I discover that classCreator use slashed type and methodCreator used jvm types (thanks to methodDescriptor). I do not touch it because it have impact on public API but I translate each time I need. I was thinking to introduce a class Descriptor... for consistency
- I put deprecated on signature setter 
- I introduce a pseudo format to add generics in method return type. It is just an idea (not very happy of it currently) idea is to have "List<String>" which produce List return for descriptor and keep generics. I am thinking to remove it totally. It was during my early code. But prefer to know if I can work to improve that and keep it and just throw it.

basic API is
```
//public <K> String transform(K thing) { return K.toString());
// signature must be <K:Ljava/lang/Object;>(TK;)Ljava/lang/String;"
try (ClassCreator creator = ClassCreator.builder().classOutput(cl).className("com.MyTest").formalType("K").build()) {
    MethodCreator method = creator.getMethodCreator("transform", "java.lang.String", "K").formalType("K");
    ResultHandle message = method.invokeStaticMethod(MethodDescriptor.ofMethod(Object.class.getName(), "toString", "Ljava/lang/String;"));
    method.returnValue(message);
}
```
I was thinking to a system to forward formalType from creator to method but it is not that simple. because some methods needs it and other don't. But Idea was to add it to classCreator and auto add to method if param used it but for that I must be able to go to classCreator from methodCreator if I have param with one letter and match with class one.
Anyway, can be a feature for futur.

**Comment by mkouba** [comment]
I think that this issue was resolved in https://github.com/quarkusio/gizmo/pull/147.
